In [1]:
#Importamos librerias
from gensim.models import word2vec
import numpy as np
import gensim

In [2]:
archivo = open('comentarios_atencion_cliente sin_etiquetas.csv','r').readlines()

In [19]:
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [22]:
stop_words=set(stopwords.words("spanish"))
def limpiezaTotal(arch):
    arch1=" ".join(arch)
    arch2=arch1.replace(";","")
    arch3=arch2.replace("\n","")
    arch4=arch3.strip(" ")
    arch5=arch4.lower()
    arch6=word_tokenize(arch5)
    arch7=filter(lambda x: x not in stop_words, arch6) #Quitamos Stopwords
    a = list(arch7)#Convertimos a lista
    return(a)

In [25]:
archivo_limpio = limpiezaTotal(archivo)

In [26]:
archivo_limpio

['datos',
 'totalmente',
 'satisfecho',
 'x',
 'q',
 'resolvieron',
 'consulta',
 'x',
 'q',
 'atencion',
 'buena',
 'dudas',
 'respondidas',
 'atencion',
 'rapida',
 'clara',
 'atendieron',
 'bien',
 'rapido',
 'atencion',
 'atendieron',
 'amablemente',
 'buena',
 'actitud',
 'plataforma',
 'cajero',
 'atendieron',
 'bien',
 'mucha',
 'atencion',
 'atencion',
 'señoritas',
 'entrada',
 'buena',
 'momento',
 'supieron',
 'guiarme',
 'varios',
 'cajerosas',
 'agencia',
 'relativamente',
 'grande',
 'buena',
 'atencion',
 'atencion',
 'rapida',
 'toma',
 'tiempo',
 'atencion',
 'sido',
 'excelente',
 'buena',
 'atencion',
 'caja',
 'atencion',
 'rapidez',
 'atencion',
 'rapida',
 'precisa',
 'q',
 'personal',
 'eficiente',
 'hacen',
 'avanzar',
 'cola',
 'rapido',
 'atencion',
 'bastante',
 'cordial',
 'trabajadora',
 'amable',
 'realize',
 'varias',
 'consultas',
 'verdad',
 'gusto',
 'recibi',
 'atencion',
 'amable',
 'ingrese',
 'agencia',
 'derivaron',
 'persona',
 'indicada',
 'atie

In [27]:
#seguimos limpiando caracteres que son menores a 3 los quitamos
c=[]
for i in archivo_limpio:
    if len(i)>=3:
        c.append(i)
b = " ".join(c)

In [29]:
#Cargamos las sentences de la base text8
sentences = word2vec.Text8Corpus('text8')

In [30]:
#Creamos el modelo
model = word2vec.Word2Vec(sentences, size=200,min_count=2)

In [31]:
#Guardamos el modelo
model.save('text8_pc4.bin')

In [32]:
#Guardamos el modelo en formato binario pues es mas rapida la entrada y es menos pesado
model.wv.save_word2vec_format('text8_pc4.bin', binary=True)

In [33]:
#Funcion que convierte String en Vector Caracteristico
def getFV(document):#document es una cadena de palabras
    
    words=document.split()#lista de palabras separadas
    s=np.zeros(200)
    k=0#contador
    for w in words:#para cada palabra que esta dentro de words
        if w in model.wv.vocab:#si la palabra estsa la encuentra y la suma
            s=s+model[w]
            k=k+1
    
    return s/k#retorna el promedio el vector caracteristico del documento

In [34]:
#Probamos la funcion getFV con la lista de palabras
getFV(b)

/home/usuariolab/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':


array([ 0.02687746, -0.14310687,  0.2194616 ,  0.03318662, -0.08699326,
        0.11879384, -0.04914158,  0.05520685, -0.01080077, -0.13402536,
       -0.04461789,  0.20229517,  0.06354801, -0.0816044 , -0.16188481,
        0.05457788, -0.07634487, -0.04131403,  0.14705984,  0.09474584,
       -0.05731841, -0.1507958 ,  0.04866939, -0.01279104, -0.05056222,
       -0.01177855, -0.09696959,  0.14183251, -0.08102704,  0.11404844,
        0.03272374, -0.15475151, -0.07354481, -0.0242406 , -0.02886368,
       -0.15292952,  0.11984092, -0.05674957, -0.15237536,  0.12182689,
       -0.02253969,  0.12082352,  0.02345363,  0.00952102, -0.12744571,
       -0.0688734 , -0.00806308, -0.16878384,  0.01069333, -0.02411944,
       -0.01732946, -0.11910661, -0.00293784,  0.00942519,  0.10616849,
        0.10301459,  0.08750895, -0.07297613, -0.0094143 ,  0.05602475,
        0.05387119,  0.03332412,  0.03461587,  0.11716218,  0.04790013,
       -0.04262284, -0.05443056, -0.19477426,  0.03740071, -0.00

In [ ]:
#archivo_final = open("data.txt", "w") 

In [35]:
#Creamos un archivo que almacenará la lista de palabras limpias del conjunto de comentarios
with open("data1.txt", 'w', encoding ='utf8') as f:  
            f.write(b)

In [36]:
#Probamos que el archivo fue guardado correctamente
archivoprueba = open("data1.txt", 'r').readlines()

In [37]:
#Creamos un sentences el cual será usado en el modelo para reentrenarlo
sentences2 = word2vec.Text8Corpus("data1.txt")

In [38]:
sentences2

In [39]:
#Anadimos el Sentences al modelo
model.build_vocab(sentences2,update=True)

In [40]:
#Entrenamos el modelo con el nuevo sentences, pues contiene datos nuevos en ESP para poder clasificar
model.train(sentences2, total_examples=model.corpus_count, epochs=model.iter) #reentrenamos el modelo con las palabras añadidas

/home/usuariolab/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `iter` (Attribute will be removed in 4.0.0, use self.epochs instead).
  


(435720, 557590)

In [41]:
#Verificamos que el modelo esta funcionando correctamente. Esto se hace con lo siguiente:
model.most_similar(['servicio'])

/home/usuariolab/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  


[('cajeros', 0.9805223345756531),
 ('fila', 0.9787325859069824),
 ('informacion', 0.9776021242141724),
 ('problema', 0.9774182438850403),
 ('buen', 0.9762576818466187),
 ('siempre', 0.9757086038589478),
 ('cliente', 0.9755666255950928),
 ('sistema', 0.975425124168396),
 ('tiempo', 0.9752037525177002),
 ('dieron', 0.9751696586608887)]

In [42]:
#Creamos una lista que contendra lista de comentarios limpios
m = []
for i in archivo:
    a = str(i)
    b=a.replace(";","")
    c = b.replace("\n","")
    d = c.strip(' ')
    e = d.replace("  ", " ")
    f = e.lower()
    m.append(f)

In [43]:
#Creamos una lista que contendra los arrays caracteristicos usando la funcion getFV
X=[]
for w in m:
    a=getFV(w)
    X.append(a)

/home/usuariolab/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':
/home/usuariolab/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


In [44]:
len(X)#Verificamos el tamaño de la lista de vectores caracteristicos

13291

In [ ]:
#Podemos usar la siguiente operacion para poder obtener la lista limpia sin NaN
#Si cambiamos if not por if podemos obtener solo la lista de NaN
#No se uso esta operacion pues para terminos de analisis de Machine Learnin era necesario mantener las listas con
#Archivos NaN
#import math
#res2 = [t for t in X if not any(isinstance(n, float) and math.isnan(n) for n in t)]

In [ ]:
#len(res2)

In [45]:
#Limpiamos la lista de vectores caracteristicos pues hay datos que al no encontralos los vuelve vectores NaN
#Esto lo hacemos con
b = np.where(np.isnan(X), 0, X)
#aqui encuentra los nan y los reemplaza por ceros. Cuestion que no sesga mucho pues solo hemos identificado que son 20

In [46]:
#Verificamos que la nueva lista limpia tiene el mismo tamaño
len(b)

13291

In [47]:
len(X)#Verificamos nuevamente el tamaño de las listas

13291

In [48]:
#Importamos la libreria de KMeans 
from sklearn.cluster import KMeans

In [49]:
#Hacemos KMeans de 2 K para b
est = KMeans(2)
est.fit (b)
y_mean=est.predict(b)

In [50]:
y_mean#es el modelo

array([1, 1, 0, ..., 0, 0, 0], dtype=int32)

In [51]:
#Abrimos el archivo de positivos para verificar el Accuracy
archivoPOSI = open('Positive.csv','r').readlines()

In [52]:
#Creamos una lista de los comentarios positivos
POSI = []
for i in archivoPOSI:
    g = str(i)
    h = g.replace(";","")
    i = h.replace("\n","")
    j = i.strip(' ')
    k = j.replace("  ", " ")
    l = k.lower()
    POSI.append(l)

In [53]:
#Usando getFV appendamos los vectores caracteristicos en una lista P de positivos
P=[]
t=0
for w in POSI:
    a=getFV(w)
    P.append(a)

/home/usuariolab/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':
/home/usuariolab/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


In [54]:
#Limpiamos la lista y convertimos los NaN en Ceros
p_ = np.where(np.isnan(P), 0, P)

In [55]:
#Hacemos KMeans para la lista p_ la cual contiene los vectores caracteristicos de los comentarios positivos
estp = KMeans(2)
estp.fit (p_)
y_meanp=estp.predict(p_)

In [56]:
y_meanp # POSITIVOS K MEANS

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1], dtype=int32)

In [57]:
#Hallamos el Accuracy de los positivos usando el algoritmo KMeans
upk=0
for i in y_meanp:
    if i == 1:
        upk=upk+1
print (upk/(len(y_meanp)))

0.4489795918367347


In [58]:
#Abrimos el archivo de negativos para verificar el Accuracy
archivoNEGA = open('Negative.csv','r').readlines()

In [59]:
#Creamos una lista de los comentarios positivos y la limpiamos
NEGA = []
for i in archivoNEGA:
    g = str(i)
    h = g.replace(";","")
    i = h.replace("\n","")
    j = i.strip(' ')
    k = j.replace("  ", " ")
    l = k.lower()
    NEGA.append(l)

In [60]:
#Usando getFV appendamos los vectores caracteristicos en una lista P de negativos
N=[]
for w in NEGA:
    a=getFV(w)
    N.append(a)

/home/usuariolab/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':


In [61]:
#Limpiamos la lista n y convertimos los NaN en Ceros
n_ = np.where(np.isnan(N), 0, N)

In [62]:
#Hallamos el Accuracy de los negativos usando el algoritmo KMeans
estn = KMeans(2)
estn.fit (n_)
y_meann=estn.predict(n_)

In [63]:
y_meann #NEGATIVOS K MEANS

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1], dtype=int32)

In [64]:
#Usando getFV appendamos los vectores caracteristicos en una lista P de negativos
unk=0
for i in y_meann:
    if i == 1:
        unk=unk+1
print (unk/(len(y_meann)))

0.82


In [65]:
#Abrimos el csv etiquetado
archivoSVM = open('label-comments_1400.csv','r').readlines()

In [66]:
#Importamos la libreria pandas. Creamos el dataframe
import pandas as pd
df = pd.read_csv('label-comments_1400.csv', delimiter = ';', header=None)

In [67]:
#Creamos data frame con solo las columnas necesarias solo para ser ordenados
df2 = df.drop(columns=[2,3,4,5])

In [68]:
etiquetas = df2[0]#data frame de solo las etiquetas
comments = df2[1]#data frame de solo los comentarios

In [69]:
#Creamos la lista para limpiarla
c_c = []
for i in comments:
    g = str(i)
    h = g.replace(";","")
    i = h.replace("\n","")
    j = i.strip(' ')
    k = j.replace("  ", " ")
    l = k.lower()
    c_c.append(l)

In [70]:
#Creamos la lista que contendra los vectores caracteristicos de todos los comentarios
co_v=[]
for w in c_c:
    a=getFV(w)
    co_v.append(a)

/home/usuariolab/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':
/home/usuariolab/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


In [71]:
#Limpiamos la lista de los NaN y lo convertimos en ceros
d=np.where(np.isnan(co_v), 0, co_v)

In [72]:
#Algoritmo de Support Vector Machine
from sklearn import svm
clasificador = svm.SVC(gamma=0.00001,C=10)

In [73]:
#Ejecutamos el clasificador SVM donde d es la lista de FV de los comentarios y etiquetas, las etiquetas
clasificador.fit(d,etiquetas)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=1e-05, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [74]:
Y_predNEGAS = clasificador.predict(n_) #NEGATIVOS SVM

In [75]:
Y_predNEGAS #Imprimimos el array de negativos con SVM

array([1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1])

In [76]:
#Hallamos el Accuracy de los negativos con SVM
un=0
for i in Y_predNEGAS:
    if i == 1:
        un=un+1
print (un/(len(Y_predNEGAS)))

0.8


In [77]:
Y_predPOSI = clasificador.predict(p_) #POSITIVOS SVM

In [78]:
Y_predPOSI #Imprimimos el array de Positivos con SVM

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [80]:
#Hallamos el Accuracy de los negativos con SVM
up=0
for i in Y_predPOSI:
    if i == 1:
        up=up+1
print (up/(len(Y_predPOSI)))

0.9795918367346939
